# Generated by Django 3.2.8 on 2024-04-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikers',
        ),
    ]
